# Generated by Django 6.0 on 2025-12-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
