# Generated by Django 6.0 on 2025-12-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0002_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
