# Generated by Django 6.0 on 2025-12-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0003_admin_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
