# Generated by Django 6.0 on 2025-12-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0004_admin_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='address',
        ),
    ]
