# Generated by Django 6.0 on 2025-12-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0008_add_timestamps_to_all_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
